<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>96e866a9-f81b-49f5-8b7f-a6edf98a8a26</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiQaLab.Core\AiQaLab.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.40.0" />
    <PackageReference Include="Google.GenAI" Version="1.18.0" />
  </ItemGroup>

</Project>
